   ## Scatter Matrix :- is a estimation of covariance matrix when covariance cannot be calculated of costly to calculated.

In [2]:
import numpy as np

In [6]:
# Create a 3 X 20 matrix with random values.
mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
samples = np.random.multivariate_normal(mu_vec1, cov_mat1, 20).T

# compute the means vector
mean_x = np.mean(samples[0,:])
mean_y = np.mean(samples[1,:])
mean_z = np.mean(samples[2,:])

mean_vector = np.array([[mean_x],[mean_y],[mean_z]])

# computation of scatter plot 
scatter_matrix = np.zeros((3,3))
for i in range(samples.shape[1]):
    scatter_matrix += (samples[:,i].reshape(3,1) - mean_vector).dot((samples[:,i].reshape(3,1) - mean_vector).T)
print('Scatter Matrix:\n',scatter_matrix)

Scatter Matrix:
 [[38.1244755  14.80509684 -6.03270449]
 [14.80509684 23.06193182 -1.87663257]
 [-6.03270449 -1.87663257 15.20752248]]


In [10]:
arrange = np.arange(0,40)
samples = np.array([arrange * 3, arrange * -1])

scatter_matrix = np.zeros((2,2))
for i in range (samples.shape[1]):
    scatter_matrix += (samples[:,i].reshape(2,1) - mean_vector).dot((samples[:,1].reshaoe(2,1) - mean_vector).T)
print('Scatter Matrix :\n',scatter_matrix)    


ValueError: operands could not be broadcast together with shapes (2,1) (3,1) 