In [2]:
import numpy as np

In [24]:
#  Write a NumPy program to compute the multiplication of two given matrixes. 
a = np.array ([[1,2,3],
              [5,6,7],
              [2,3,5]])
b = np.array ([[1,2,3],
              [5,6,7],
              [2,3,5]])
# dot product specifies the matrix multiplication
print(np.dot(a,b))

[[17 23 32]
 [49 67 92]
 [27 37 52]]


In [25]:
#Write a NumPy program to compute the outer product of two given vectors.
v1 = np.array([[1],
              [2],
              [3],
              [4]])
v2 = np.array([[6],
              [7],
              [8],
              [9]])

print(np.outer(v1,v2))


[[ 6  7  8  9]
 [12 14 16 18]
 [18 21 24 27]
 [24 28 32 36]]


In [26]:
#Write a NumPy program to compute the cross product of two given vectors.
v1 = np.array([2,-1,3])
v2 = np.array([3,4,5])

print(np.cross(v1,v2))

[-17  -1  11]


In [29]:
#Write a NumPy program to compute the determinant of a given square array.
mat1 = np.array([[4,2],
                [1,1]])
print(np.linalg.det(mat1))

2.0


In [45]:
#Write a NumPy program to evaluate Einstein's summation convention of two given multidimensional arrays. 
a = np.array([0,1,2])
b = np.array([[0,1,2,3],
             [4,5,6,7],
             [8,9,10,11]])
print((a[:,np.newaxis]*b).sum(axis=1))
print(np.einsum('i,ij->i',a,b))

[ 0 22 76]
[ 0 22 76]


In [52]:
A = np.array([[1, 1, 1],
           [2, 2, 2],
           [5, 5, 5]])

B = np.array([[0, 1, 0],
           [1, 1, 0],
           [1, 1, 1]])
print(np.einsum('ij,jk->ijk',A,B))
print(np.einsum('ij,jk->ik',A,B))
print(np.einsum('ij->',A))

[[[0 1 0]
  [1 1 0]
  [1 1 1]]

 [[0 2 0]
  [2 2 0]
  [2 2 2]]

 [[0 5 0]
  [5 5 0]
  [5 5 5]]]
[[ 2  3  1]
 [ 4  6  2]
 [10 15  5]]
24


In [53]:
#Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension.
a = np.array([6,5])   #this is vector a
b = np.array([2,4]) # this is vector b
print(np.inner(a,b))

32


In [56]:
#7. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.
from numpy import linalg as la
a = np.array (([[1, -1], [1, 1]]))
print(la.eig(a))
#here first matrix is eigen value and another is eigen vector


(array([1.+1.j, 1.-1.j]), array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]]))


In [58]:
#8. Write a NumPy program to compute the Kronecker product of two given mulitdimension arrays.
a = np.array([[1,2],
             [3,4]])
b = np.array([[0,5],
             [6,7]])
print(np.kron(a,b))

[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


In [66]:
# 9. Write a NumPy program to compute the condition number of a given matrix. 
from numpy import linalg as la
a = np.array([[1,2],
             [3,4]])
print(la.cond(a))
print(la.inv(a))

14.933034373659268
[[-2.   1. ]
 [ 1.5 -0.5]]


In [67]:
# Write a NumPy program to find a matrix or vector norm.
a = np.array([[1,2],
             [3,4]])
print(la.norm(a))

5.477225575051661


In [68]:
#Write a NumPy program to compute the inverse of a given matrix. 
a = np.array([[1,2],
             [3,4]])
print(la.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [70]:
#Write a NumPy program to compute the determinant of an array.
a = np.array([[4,1],
             [3,4]])
print(la.det(a))


13.0


In [71]:
#Write QR decomposition of a matrix
m = np.array([[1,2],
            [2,3]])
print("Original matrix")
print(m)
print("QR decomposition ")
print(la.qr(m))

Original matrix
[[1 2]
 [2 3]]
QR decomposition 
(array([[-0.4472136 , -0.89442719],
       [-0.89442719,  0.4472136 ]]), array([[-2.23606798, -3.57770876],
       [ 0.        , -0.4472136 ]]))


In [3]:
# Write numpy program for sum of diagonal elements 
mat1 = np.array([[1,0,0],
                [0,1,0],
                 [0,0,1]])
print("Original Matrix")
print(mat1)
print("Diagonal elements")
print(mat1.diagonal())
print("Sum of diagonal")
print(mat1.diagonal().sum())
print("Use Trace ")
print(np.trace(mat1))

Original Matrix
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Diagonal elements
[1 1 1]
Sum of diagonal
3
Use Trace 
3
